#!/usr/bin/env python3
# ==================================================================
#
#                    DEVELOPMENT STATISTICS
#
# Prints (and writes to STATS.md) per-directory statistics for the
# proof development: lines of code and declaration counts.  EVERY
# number is computed from the sources at generation time — nothing is
# hardcoded, so a paper citing these figures can regenerate them with
# `make stats` and diff against the committed STATS.md.
#
# Declaration counting is syntactic: a line whose first token (after
# leading whitespace) is the keyword.  Comment prose never starts a
# line with a bare declaration keyword in this codebase, and the
# repo uses no Local/Program/Global prefixes (checked 2026-07-19).
#
# ==================================================================
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTFILE = "STATS.md"

DIRS = ["core", "subst", "safety", "examples"]
KEYWORDS = ["Definition", "Fixpoint", "Inductive", "Lemma", "Theorem", "Corollary"]

# A declaration line starts (after optional whitespace) with the
# keyword followed by a whitespace character.
KW_RE = {kw: re.compile(r"^\s*" + kw + r"\s") for kw in KEYWORDS}


def main():
    out = []
    out.append("# Development statistics")
    out.append("")
    out.append("Generated by `make stats` — do not edit by hand; every number")
    out.append("is computed from `src/` at generation time.")
    out.append("")
    out.append("| Directory | Files | LOC |" + "".join(f" {kw} |" for kw in KEYWORDS))
    out.append("| --- | ---: | ---: |" + " ---: |" * len(KEYWORDS))

    total_files = 0
    total_loc = 0
    total_kw = {kw: 0 for kw in KEYWORDS}

    for d in DIRS:
        # Byte-wise sort (à la LC_ALL=C) for determinism.
        files = sorted(ROOT.joinpath("src", d).rglob("*.v"), key=str)
        text = "".join(
            f.read_text(encoding="utf-8", errors="replace") for f in files
        )
        loc = text.count("\n")
        row = f"| {d} | {len(files)} | {loc} |"
        for kw in KEYWORDS:
            c = sum(1 for line in text.split("\n") if KW_RE[kw].match(line))
            row += f" {c} |"
            total_kw[kw] += c
        out.append(row)
        total_files += len(files)
        total_loc += loc

    out.append(
        f"| **total** | {total_files} | {total_loc} |"
        + "".join(f" {total_kw[kw]} |" for kw in KEYWORDS)
    )

    content = "\n".join(out) + "\n"
    (ROOT / OUTFILE).write_text(content, encoding="utf-8")
    print(content, end="")
    print()
    print(f"Wrote {OUTFILE}.")


if __name__ == "__main__":
    main()
