#!/usr/bin/env python3
# ==================================================================
#
#                    DEVELOPMENT STATISTICS
#
# Prints (and writes to STATS.md) per-directory statistics for the
# proof development: lines of code and declaration counts.  EVERY
# number is computed from the sources at generation time — nothing is
# hardcoded (the directory list comes from src/_CoqProject), so a
# paper citing these figures can regenerate them with `make stats`
# and diff against the committed STATS.md.  `--check` (used by
# `make check-docs` / `make verify`) fails when the committed file
# is stale.
#
# Declaration counting is syntactic: a line whose first token (after
# leading whitespace) is the keyword.  Local/Program/Global-prefixed
# declaration forms would evade that counting, so their absence is
# CHECKED (guard_no_prefixed_decls), not assumed.
#
# ==================================================================
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import coqparse

ROOT = coqparse.ROOT
OUTFILE = "STATS.md"

KEYWORDS = coqparse.STAT_KEYWORDS

# A declaration line starts (after optional whitespace) with the
# keyword followed by a whitespace character.
KW_RE = {kw: re.compile(r"^\s*" + kw + r"\s") for kw in KEYWORDS}


def main():
    check_mode = "--check" in sys.argv[1:]

    dirs = coqparse.coq_project_dirs()

    # Prefixed declarations would silently undercount; fail loudly.
    bad = []
    for d in dirs:
        for f in sorted((ROOT / "src" / p for p in coqparse.coq_project_files()
                         if p.parts[0] == d), key=str):
            for ln, line in coqparse.guard_no_prefixed_decls(f):
                bad.append(f"{f.relative_to(ROOT)}:{ln}: {line}")
    if bad:
        print("FAIL: prefixed declarations found — the keyword counting "
              "below would miss them; extend stats.py first:",
              file=sys.stderr)
        for b in bad:
            print(f"  {b}", file=sys.stderr)
        sys.exit(1)

    out = []
    out.append("# Development statistics")
    out.append("")
    out.append("Generated by `make stats` — do not edit by hand; every number")
    out.append("is computed from `src/` at generation time.")
    out.append("")
    out.append("| Directory | Files | LOC |" + "".join(f" {kw} |" for kw in KEYWORDS))
    out.append("| --- | ---: | ---: |" + " ---: |" * len(KEYWORDS))

    total_files = 0
    total_loc = 0
    total_kw = {kw: 0 for kw in KEYWORDS}

    project_files = coqparse.coq_project_files()
    for d in dirs:
        # Files of the build only (from _CoqProject), byte-wise sorted
        # (à la LC_ALL=C) for determinism.
        files = sorted((ROOT / "src" / f for f in project_files
                        if f.parts[0] == d), key=str)
        text = "".join(
            f.read_text(encoding="utf-8", errors="replace") for f in files
        )
        loc = text.count("\n")
        row = f"| {d} | {len(files)} | {loc} |"
        for kw in KEYWORDS:
            c = sum(1 for line in text.split("\n") if KW_RE[kw].match(line))
            row += f" {c} |"
            total_kw[kw] += c
        out.append(row)
        total_files += len(files)
        total_loc += loc

    out.append(
        f"| **total** | {total_files} | {total_loc} |"
        + "".join(f" {total_kw[kw]} |" for kw in KEYWORDS)
    )

    content = "\n".join(out) + "\n"
    if not coqparse.check_or_write(OUTFILE, content, check_mode, "stats"):
        sys.exit(1)
    if not check_mode:
        print(content, end="")
        print()
        print(f"Wrote {OUTFILE}.")


if __name__ == "__main__":
    main()
