#!/usr/bin/env bash
# ==================================================================
#
#                    DEVELOPMENT STATISTICS
#
# Prints (and writes to STATS.md) per-directory statistics for the
# proof development: lines of code and declaration counts.  EVERY
# number is computed from the sources at generation time — nothing is
# hardcoded, so a paper citing these figures can regenerate them with
# `make stats` and diff against the committed STATS.md.
#
# Declaration counting is syntactic: a line whose first token (after
# leading whitespace) is the keyword.  Comment prose never starts a
# line with a bare declaration keyword in this codebase, and the
# repo uses no Local/Program/Global prefixes (checked 2026-07-19).
#
# ==================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
OUTFILE="STATS.md"

DIRS=(core subst safety examples)
KEYWORDS=(Definition Fixpoint Inductive Lemma Theorem Corollary)

# count_kw <keyword> <file...> — occurrences of keyword-led lines.
# grep -c exits 1 on zero matches; `|| true` keeps set -e happy.
count_kw() {
  local kw="$1"; shift
  cat "$@" | grep -Ec "^[[:space:]]*${kw}[[:space:]]" || true
}

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Development statistics"
  echo
  echo "Generated by \`make stats\` — do not edit by hand; every number"
  echo "is computed from \`src/\` at generation time."
  echo
  printf '| Directory | Files | LOC |'
  for kw in "${KEYWORDS[@]}"; do printf ' %s |' "$kw"; done
  printf '\n'
  printf '| --- | ---: | ---: |'
  for kw in "${KEYWORDS[@]}"; do printf ' ---: |'; done
  printf '\n'

  total_files=0; total_loc=0
  declare -A total_kw
  for kw in "${KEYWORDS[@]}"; do total_kw[$kw]=0; done

  for d in "${DIRS[@]}"; do
    # LC_ALL=C sort for determinism; mapfile keeps paths word-split-safe.
    mapfile -t files < <(find "src/$d" -name '*.v' | LC_ALL=C sort)
    nfiles="${#files[@]}"
    loc="$(cat "${files[@]}" | wc -l)"
    printf '| %s | %d | %d |' "$d" "$nfiles" "$loc"
    for kw in "${KEYWORDS[@]}"; do
      c="$(count_kw "$kw" "${files[@]}")"
      printf ' %d |' "$c"
      total_kw[$kw]=$(( total_kw[$kw] + c ))
    done
    printf '\n'
    total_files=$(( total_files + nfiles ))
    total_loc=$(( total_loc + loc ))
  done

  printf '| **total** | %d | %d |' "$total_files" "$total_loc"
  for kw in "${KEYWORDS[@]}"; do printf ' %d |' "${total_kw[$kw]}"; done
  printf '\n'
} > "$TMP"

cp "$TMP" "$OUTFILE"
cat "$OUTFILE"
echo
echo "Wrote $OUTFILE."
