#!/usr/bin/env bash
# ==================================================================
#
#                     THEOREM INDEX GENERATOR
#
# Regenerates THEOREMS.md: a table of every Theorem and Corollary
# (deliberately NOT plain Lemmas — those are internal machinery)
# across src/**/*.v, with name, file:line, and the first line of the
# statement.  Output is deterministic: files are sorted with LC_ALL=C
# and rows follow source line order within each file, so regenerating
# on an unchanged tree is a no-op — CI-friendly and diff-reviewable.
#
# Run via `make theorem-index`.  THEOREMS.md is committed; regenerate
# it whenever a Theorem/Corollary is added, moved, or renamed.
#
# ==================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
OUTFILE="THEOREMS.md"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# One table row per Theorem/Corollary.  awk details:
#  - the statement's first line is what follows the first ':' on the
#    declaration line; when the declaration line ends at the colon
#    (e.g. "Theorem type_soundness :"), take the next source line;
#  - '|' is escaped for the Markdown table, and statements are wrapped
#    in double-backtick code spans padded with spaces so that inline
#    backticks in the calculus notation (`Ll, `Lf) survive rendering.
find src -name '*.v' | LC_ALL=C sort | while IFS= read -r f; do
  awk -v file="$f" '
    /^[[:space:]]*(Theorem|Corollary)[[:space:]]/ {
      ln = NR
      name = $2
      sub(/:.*/, "", name)
      stmt = $0
      sub(/^[[:space:]]*(Theorem|Corollary)[[:space:]]+[^:]*:[[:space:]]*/, "", stmt)
      if (stmt ~ /^[[:space:]]*$/) {
        if ((getline nxt) > 0) stmt = nxt
      }
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", stmt)
      gsub(/\|/, "\\|", stmt)
      printf("| `%s` | `%s:%d` | `` %s `` |\n", name, file, ln, stmt)
    }
  ' "$f"
done > "$TMP"

n_rows="$(wc -l < "$TMP")"

{
  echo "# Theorem index"
  echo
  echo "Every \`Theorem\` and \`Corollary\` in \`src/\` ($n_rows total)."
  echo "Plain \`Lemma\`s are internal machinery and are not listed."
  echo
  echo "Generated by \`make theorem-index\` — do not edit by hand."
  echo
  echo "| Name | Location | Statement (first line) |"
  echo "| --- | --- | --- |"
  cat "$TMP"
} > "$OUTFILE"

echo "Wrote $OUTFILE ($n_rows theorems/corollaries)."
