#!/usr/bin/env python3
# ==================================================================
#
#                     THEOREM INDEX GENERATOR
#
# Regenerates THEOREMS.md: a table of every Theorem and Corollary
# (deliberately NOT plain Lemmas — those are internal machinery)
# across src/**/*.v, with name, file:line, and the first line of the
# statement.  Output is deterministic: files are sorted byte-wise
# and rows follow source line order within each file, so regenerating
# on an unchanged tree is a no-op — CI-friendly and diff-reviewable.
#
# Run via `make theorem-index`.  THEOREMS.md is committed; regenerate
# it whenever a Theorem/Corollary is added, moved, or renamed.
#
# ==================================================================
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTFILE = "THEOREMS.md"

DECL_RE = re.compile(r"^\s*(Theorem|Corollary)\s")
# The statement's first line is what follows the first ':' on the
# declaration line.
STMT_RE = re.compile(r"^\s*(Theorem|Corollary)\s+[^:]*:\s*")


def rows_for_file(path, relpath):
    """One table row per Theorem/Corollary in the file.

    When the declaration line ends at the colon (e.g. "Theorem
    type_soundness :"), the statement is taken from the next source
    line.  '|' is escaped for the Markdown table, and statements are
    wrapped in double-backtick code spans padded with spaces so that
    inline backticks in the calculus notation (`Ll, `Lf) survive
    rendering.
    """
    rows = []
    lines = path.read_text(encoding="utf-8", errors="replace").split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        if DECL_RE.match(line):
            ln = i + 1
            fields = line.split()
            name = fields[1] if len(fields) > 1 else ""
            name = name.split(":", 1)[0]
            stmt = STMT_RE.sub("", line, count=1)
            if stmt.strip() == "" and i + 1 < len(lines):
                i += 1
                stmt = lines[i]
            stmt = stmt.strip().replace("|", "\\|")
            rows.append(f"| `{name}` | `{relpath}:{ln}` | `` {stmt} `` |")
        i += 1
    return rows


def main():
    # Byte-wise sort (à la LC_ALL=C) for determinism.
    files = sorted(ROOT.joinpath("src").rglob("*.v"), key=str)
    rows = []
    for f in files:
        rows.extend(rows_for_file(f, f.relative_to(ROOT).as_posix()))

    n_rows = len(rows)
    out = [
        "# Theorem index",
        "",
        f"Every `Theorem` and `Corollary` in `src/` ({n_rows} total).",
        "Plain `Lemma`s are internal machinery and are not listed.",
        "",
        "Generated by `make theorem-index` — do not edit by hand.",
        "",
        "| Name | Location | Statement (first line) |",
        "| --- | --- | --- |",
    ] + rows

    (ROOT / OUTFILE).write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote {OUTFILE} ({n_rows} theorems/corollaries).")


if __name__ == "__main__":
    main()
